export const GET_ALLUSER_REQUEST='GET_ALLUSER_REQUEST'
export const GET_ALLUSER_SUCCESS='GET_ALLUSER_SUCCESS'
export const GET_ALLUSER_FAIL='GET_ALLUSER_FAIL'
export const GET_ALLCOLLEGES_REQUEST='GET_ALLCOLLEGES_REQUEST'
export const GET_ALLCOLLEGES_SUCCESS='GET_ALLCOLLEGES_SUCCESS'
export const GET_ALLCOLLEGES_FAIL='GET_ALLCOLLEGES_FAIL'
export const ADMIN_COLLEGE_DETAILS_REQUEST='ADMIN_COLLEGE_DETAILS_REQUEST'
export const ADMIN_COLLEGE_DETAILS_SUCCESS='ADMIN_COLLEGE_DETAILS_SUCCESS'
export const ADMIN_COLLEGE_DETAILS_FAIL='ADMIN_COLLEGE_DETAILS_FAIL'

export const UPDATE_USER_REQUEST='UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS='UPDATE_USER_SUCCESS'
export const UPDATE_USER_RESET='UPDATE_USER_RESET'
export const UPDATE_USER_FAIL='UPDATE_USER_FAIL'



export const PANDING_APPROVEL_REQUEST='PANDING_APPROVEL_REQUEST'
export const PANDING_APPROVEL_SUCCESS='PANDING_APPROVEL_SUCCESS'
export const PANDING_APPROVEL_FAIL='PANDING_APPROVEL_FAIL'

export const COLLEGE_APPROVEL_REQUEST='COLLEGE_APPROVEL_REQUEST'
export const COLLEGE_APPROVEL_SUCCESS='COLLEGE_APPROVEL_SUCCESS'
export const COLLEGE_APPROVEL_RESET='COLLEGE_APPROVEL_RESET'
export const COLLEGE_APPROVEL_FAIL='COLLEGE_APPROVEL_FAIL'



export const CLEAR_ERRORS='CLEAR_ERRORS'