export const ALL_COLLEGE_REQUEST="ALL_COLLEGE_REQUEST";
export const ALL_COLLEGE_SUCCESS="ALL_COLLEGE_SUCCESS";
export const ALL_COLLEGE_FAIL="ALL_COLLEGE_FAIL";

export const COLLEGE_DETAILS_REQUEST="COLLEGE_DETAILS_REQUEST";
export const COLLEGE_DETAILS_SUCCESS="COLLEGE_DETAILS_SUCCESS";
export const COLLEGE_DETAILS_FAIL="COLLEGE_DETAILS_FAIL";


export const CLEAR_ERRORS="CLEAR_ERRORS";