
export const ALL_COURSES_REQUEST="ALL_COURSES_REQUEST";
export const ALL_COURSES_SUCCESS="ALL_COURSES_SUCCESS";
export const ALL_COURSES_FAIL="ALL_COURSES_FAIL";
export const COURSE_DETAILS_REQUEST="COURSE_DETAILS_REQUEST";
export const COURSE_DETAILS_SUCCESS="COURSE_DETAILS_SUCCESS";
export const COURSE_DETAILS_FAIL="COURSE_DETAILS_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";