export const ADD_COURSECOVER_REQUEST="ADD_COURSECOVER_REQUEST";
export const ADD_COURSECOVER_SUCCESS="ADD_COURSECOVER_SUCCESS";
export const ADD_COURSECOVER_RESET="ADD_COURSECOVER_RESET";
export const ADD_COURSECOVER_FAIL="ADD_COURSECOVER_FAIL";
export const OTHER_COURSEPHOTO_REQUEST="OTHER_COURSEPHOTO_REQUEST";
export const OTHER_COURSEPHOTO_RESET="OTHER_COURSEPHOTO_RESET";
export const OTHER_COURSEPHOTO_SUCCESS="OTHER_COURSEPHOTO_SUCCESS";
export const OTHER_COURSEPHOTO_FAIL="OTHER_COURSEPHOTO_FAIL";
export const LOGO_UPLOAD_REQUEST="LOGO_UPLOAD_REQUEST";
export const LOGO_UPLOAD_RESET="LOGO_UPLOAD_RESET";
export const LOGO_UPLOAD_SUCCESS="LOGO_UPLOAD_SUCCESS";
export const LOGO_UPLOAD_FAIL="LOGO_UPLOAD_FAIL";
export const COLLEGELOGO_UPLOAD_REQUEST="COLLEGELOGO_UPLOAD_REQUEST";
export const COLLEGELOGO_UPLOAD_RESET="COLLEGELOGO_UPLOAD_RESET";
export const COLLEGELOGO_UPLOAD_SUCCESS="COLLEGELOGO_UPLOAD_SUCCESS";
export const COLLEGELOGO_UPLOAD_FAIL="COLLEGELOGO_UPLOAD_FAIL";
export const COLLEGE_OTHERIMG_UPLOAD_REQUEST="COLLEGE_OTHERIMG_UPLOAD_REQUEST";
export const COLLEGE_OTHERIMG_UPLOAD_RESET="COLLEGE_OTHERIMG_UPLOAD_RESET";
export const COLLEGE_OTHERIMG_UPLOAD_SUCCESS="COLLEGE_OTHERIMG_UPLOAD_SUCCESS";
export const COLLEGE_OTHERIMG_UPLOAD_FAIL="COLLEGE_OTHERIMG_UPLOAD_FAIL";
export const COLLEGE_COVERIMG_UPLOAD_REQUEST="COLLEGE_COVERIMG_UPLOAD_REQUEST";
export const COLLEGE_COVERIMG_UPLOAD_RESET="COLLEGE_COVERIMG_UPLOAD_RESET";
export const COLLEGE_COVERIMG_UPLOAD_SUCCESS="COLLEGE_COVERIMG_UPLOAD_SUCCESS";
export const COLLEGE_COVERIMG_UPLOAD_FAIL="COLLEGE_COVERIMG_UPLOAD_FAIL";

export const CAROUSEL_IMAGE_UPLOAD_REQUEST="CAROUSEL_IMAGE_UPLOAD_REQUEST";
export const CAROUSEL_IMAGE_UPLOAD_RESET="CAROUSEL_IMAGE_UPLOAD_RESET";
export const CAROUSEL_IMAGE_UPLOAD_SUCCESS="CAROUSEL_IMAGE_UPLOAD_SUCCESS";
export const CAROUSEL_IMAGE_UPLOAD_FAIL="CAROUSEL_IMAGE_UPLOAD_FAIL";
export const SCHEME_UPLOAD_REQUEST="SCHEME_UPLOAD_REQUEST";
export const SCHEME_UPLOAD_RESET="SCHEME_UPLOAD_RESET";
export const SCHEME_UPLOAD_SUCCESS="SCHEME_UPLOAD_SUCCESS";
export const SCHEME_UPLOAD_FAIL="SCHEME_UPLOAD_FAIL";

export const GET_CAROUSEL_REQUEST="GET_CAROUSEL_REQUEST";
export const GET_CAROUSEL_SUCCESS="GET_CAROUSEL_SUCCESS";
export const GET_CAROUSEL_FAIL="GET_CAROUSEL_FAIL";

export const DELETE_IMAGE_REQUEST="DELETE_IMAGE_REQUEST";
export const DELETE_IMAGE_RESET="DELETE_IMAGE_RESET";
export const DELETE_IMAGE_SUCCESS="DELETE_IMAGE_SUCCESS";
export const DELETE_IMAGE_FAIL="DELETE_IMAGE_FAIL";

export const DELETE_CAROUSEL_REQUEST="DELETE_CAROUSEL_REQUEST";
export const DELETE_CAROUSEL_RESET="DELETE_CAROUSEL_RESET";
export const DELETE_CAROUSEL_SUCCESS="DELETE_CAROUSEL_SUCCESS";
export const DELETE_CAROUSEL_FAIL="DELETE_CAROUSEL_FAIL";
export const CLEAR_ERRORS="CLEAR_ERRORS";