export const ADD_PAYMENT_REQUEST="ADD_PAYMENT_REQUEST";
export const ADD_PAYMENT_SUCCESS="ADD_PAYMENT_SUCCESS";
export const ADD_PAYMENT_RESET="ADD_PAYMENT_RESET";
export const ADD_PAYMENT_FAIL="ADD_PAYMENT_FAIL";
export const PROCESS_PAYMENT_REQUEST="PROCESS_PAYMENT_REQUEST";
export const PROCESS_PAYMENT_SUCCESS="PROCESS_PAYMENT_SUCCESS";

export const PROCESS_PAYMENT_FAIL="PROCESS_PAYMENT_FAIL";
export const COURSE_PAYMENT_HISTORY_REQUEST="COURSE_PAYMENT_HISTORY_REQUEST";
export const COURSE_PAYMENT_HISTORY_SUCCESS="COURSE_PAYMENT_HISTORY_SUCCESS";
export const COURSE_PAYMENT_HISTORY_FAIL="COURSE_PAYMENT_HISTORY_FAIL";
export const COURSE_PAYMENT_DETAILS_REQUEST="COURSE_PAYMENT_DETAILS_REQUEST";
export const COURSE_PAYMENT_DETAILS_SUCCESS="COURSE_PAYMENT_DETAILS_SUCCESS";
export const COURSE_PAYMENT_DETAILS_FAIL="COURSE_PAYMENT_DETAILS_FAIL";
export const STUDENT_NEW_PAYMENT_REQUEST="STUDENT_NEW_PAYMENT_REQUEST";
export const STUDENT_NEW_PAYMENT_SUCCESS="STUDENT_NEW_PAYMENT_SUCCESS";
export const STUDENT_NEW_PAYMENT_FAIL="STUDENT_NEW_PAYMENT_FAIL";
export const STUDENT_PAYMENT_HISTORY_REQUEST="STUDENT_PAYMENT_HISTORY_REQUEST";
export const STUDENT_PAYMENT_HISTORY_SUCCESS="STUDENT_PAYMENT_HISTORY_SUCCESS";
export const STUDENT_PAYMENT_HISTORY_FAIL="STUDENT_PAYMENT_HISTORY_FAIL";


export const CLOSED_PAYMENT_SUCCESS="CLOSED_PAYMENT_SUCCESS";
export const CLOSED_PAYMENT_REQUEST="CLOSED_PAYMENT_REQUEST";
export const CLOSED_PAYMENT_RESET="CLOSED_PAYMENT_RESET";
export const CLOSED_PAYMENT_FAIL="CLOSED_PAYMENT_FAIL";


export const CLEAR_ERRORS="CLEAR_ERRORS";