export const PREFERENCE_REGISTER_REQUEST="PREFERENCE_REGISTER_REQUEST";
export const PREFERENCE_REGISTER_SUCCESS="PREFERENCE_REGISTER_SUCCESS";
export const PREFERENCE_REGISTER_FAIL="PREFERENCE_REGISTER_FAIL";
export const CLEAR_ERRORS="CLEAR_ERRORS";